---
- hosts: localhost
  tasks:
    - name: Add docker pubkey
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Install docker packages 
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
        state: present
        update_cache: true
      become: true

    - name: Setup docker group
      group: 
        name: docker
        state: present
      become: true

    - name: Setup user with docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      become: true

