---

- hosts: localhost 
  tasks: 

  - name: Add yarn public key
    apt_key: 
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present
    become: true

  - name: Add yarn repo
    apt_repository: 
      repo: deb https://dl.yarnpkg.com/debian stable main
      state: present
    become: true

  - name: Add docker pubkey
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: Add docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
    become: true

  - name: Install packages with apt
    apt:
      name: ['neovim', 'curl', 'wget', 'httpie', 'git', 'yarn', 'docker-ce', 'docker-ce-cli', 'containerd.io']
      state: present
      update_cache: true
    become: true
  
  - name: Setup docker group
    group: 
      name: docker
      state: present
    become: true

  - name: Setup user with docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: true
    become: true

