---

- hosts: localhost 
  tasks: 

  - name: Add yarn public key
    apt_key: 
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present
    become: true

  - name: Add yarn repo
    apt_repository: 
      repo: deb https://dl.yarnpkg.com/debian stable main
      state: present
    become: true

  - name: Add docker pubkey
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: Add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install packages with apt
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - neovim
      - curl
      - wget
      - httpie
      - git
      - yarn
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    become: true
